//! # std::evolve — Evolutionary Computation
//!
//! First-class support for genetic algorithms, neuroevolution,
//! and evolutionary strategies. The `evolve` block declaratively
//! specifies population, fitness, selection, crossover, and mutation.

// ---------------------------------------------------------------------------
// Genome trait
// ---------------------------------------------------------------------------

/// A genotype that can be crossed over, mutated, and evaluated.
/// Implement via `#[derive(Genome)]` on structs.
pub trait Genome: Clone {
    /// Generate a random genome.
    pub fn random() -> Self / rng;

    /// Cross this genome with another, producing offspring.
    pub fn crossover(&self, other: &Self) -> Self / rng;

    /// Mutate this genome in place.
    pub fn mutate(&mut self, sigma: f64) / rng;
}

/// A single gene within a genome.
/// Implement via `#[derive(Gene)]` on enums.
pub trait Gene: Clone {
    /// Random gene variant.
    pub fn random() -> Self / rng;

    /// Mutate this gene.
    pub fn mutate(&mut self) / rng;
}

// ---------------------------------------------------------------------------
// Selection strategies
// ---------------------------------------------------------------------------

/// Selection strategy for choosing parents.
pub enum SelectionStrategy {
    /// Tournament selection: pick best of `k` random candidates.
    Tournament { k: usize },
    /// Roulette wheel (fitness-proportionate).
    Roulette,
    /// Rank-based selection.
    Rank,
    /// Elitist: keep top `n` unchanged.
    Elitist { n: usize },
}

// ---------------------------------------------------------------------------
// Crossover strategies
// ---------------------------------------------------------------------------

/// Crossover strategy for combining genomes.
pub enum CrossoverStrategy {
    /// Uniform crossover with a given rate.
    Uniform { rate: f64 },
    /// Single-point crossover.
    SinglePoint,
    /// Two-point crossover.
    TwoPoint,
    /// Blend crossover (for continuous values).
    Blend { alpha: f64 },
}

// ---------------------------------------------------------------------------
// Mutation strategies
// ---------------------------------------------------------------------------

/// Mutation strategy for modifying genomes.
pub enum MutationStrategy {
    /// Gaussian perturbation with standard deviation sigma.
    Gaussian { sigma: f64 },
    /// Uniform random reset with probability `rate`.
    Uniform { rate: f64 },
    /// Bit-flip mutation with probability `rate`.
    BitFlip { rate: f64 },
}

// ---------------------------------------------------------------------------
// Evolution statistics
// ---------------------------------------------------------------------------

/// Statistics for one generation.
pub struct EvolveStats {
    pub generation: u32,
    pub best_fitness: f64,
    pub mean_fitness: f64,
    pub worst_fitness: f64,
    pub diversity: f64,
    pub stagnation_count: u32,
}

// ---------------------------------------------------------------------------
// Evolution runner
// ---------------------------------------------------------------------------

/// Run an evolutionary computation.
/// Typically generated by the compiler from an `evolve` block.
pub fn run_evolution<G: Genome>(
    population_size: usize,
    generations: usize,
    fitness: fn(&G) -> f64,
    selection: SelectionStrategy,
    crossover: CrossoverStrategy,
    mutation: MutationStrategy,
    target: Option<f64>,
    on_generation: Option<fn(u32, &G, &EvolveStats)>,
) -> G / rng;

// ---------------------------------------------------------------------------
// Population
// ---------------------------------------------------------------------------

/// A population of genomes.
pub struct Population<G: Genome> {
    individuals: Vec<G>,
    fitnesses: Vec<f64>,
}

impl<G: Genome> Population<G> {
    /// Create a random initial population.
    pub fn random(size: usize) -> Population<G> / rng;

    /// Get the fittest individual.
    pub fn best(&self) -> &G;

    /// Get statistics.
    pub fn stats(&self) -> EvolveStats;

    /// Evolve one generation.
    pub fn step(
        &mut self,
        fitness: fn(&G) -> f64,
        selection: &SelectionStrategy,
        crossover: &CrossoverStrategy,
        mutation: &MutationStrategy,
    ) / rng;
}
